apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qia2v78xn-nodejs 
  janus-idp.io/tekton: qia2v78xn-nodejs
  backstage.io/kubernetes-id: qia2v78xn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qia2v78xn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml